using System;

namespace Tools.Audio
{
	public enum AudioState
	{
		COMPONENT_INACTIVE,
		INITIALIZATION_ERROR,
		TRACK_RUNNING,
		TRACK_STOPPED,
		TOOL_EXCEPTION,
		NO_TARGET_SELECTED,
		NO_PARAMETERS_INSERTED,
		INVALID_TRACK_ID,
		WAITING_FOR_TRIGGER,
		LOGIC_TRIGGERED
	}
}
